#!/bin/bash

# almod : change alacritty's config file

TPATH=".local/share/alacritty_themes"

# set opacity value
set_value () {
  sed -Ei "s/^(background_opacity: )(.*)/\1$1/"\
  $HOME/.config/alacritty/alacritty.yml
}

# get opacity value 
opacity () {
  [ -z "$(grep '^background_opacity:' $HOME/.config/alacritty/alacritty.yml)" ] && echo "background_opacity: 0.8" >> $HOME/.config/alacritty/alacritty.yml && exit
  VALUE=$(grep '^background_opacity:' $HOME/.config/alacritty/alacritty.yml |
  sed 's/^background_opacity: //')
  [[ $VALUE == 1.0 && $1 == +1 ]] && set_value 0.0 && exit ||
  [[ $VALUE == 1.0 && $1 == -1 ]] && set_value 0.9 && exit ||
  [[ $VALUE == 0.9 && $1 == +1 ]] && set_value 1.0 && exit ||
  [[ $VALUE == 0.0  && $1 == -1 ]] && set_value 1.0 && exit ||
  set_value 0.$((${VALUE/0./}$1))
}

# download themes
get_themes () {
  [ ! -d $TPATH ] && mkdir -p $TPATH && echo "$TPATH sucessfully created."
  THEMES=$(curl -s https://github.com/eendroroy/alacritty-theme/tree/master/themes)
  for i in $(grep -Eo '/eendroroy/alacritty-theme/blob/master/themes/[_[:alnum:]-]*.(yaml|yml)' <<< "$THEMES" | sed 's|^|https://raw.githubusercontent.com|; s|/blob||'); do
   echo "Downloading $(cut -d "/" -f8 <<< "$i")"
   wget -q "$i" -O $TPATH/$(cut -d "/" -f8 <<< "$i")
   sed -i '/^  *$/d; /^$/d; /^ *#/d' $TPATH/$(cut -d "/" -f8 <<< "$i")
  done
}

# set random theme
set_theme () {
  [ -z $1 ] && FILE=$(cat $(find $TPATH -mindepth 1| shuf -n1)) || FILE==$(cat $@)
  [ -z "$(grep '^colors:' $HOME/.config/alacritty/alacritty.yml)" ] && add_theme && exit
while IFS= read -r LINE; do
  VALUE="${LINE/:*/:}"
  while IFS= read -r VAL; do
    sed -i "s|^$VAL.*$|$LINE|" $HOME/.config/alacritty/alacritty.yml
  done <<< "$VALUE"
done <<< "$FILE"
}

pick_theme () {
  set_theme $(find $TPATH -type f | sed -E 's|^.*/(.*)\.y.*|\1|' | dmenu | xargs -I '{}' find $TPATH -name '*{}*')
}

# add theme for the first time
add_theme () {
  cat $(find $TPATH -mindepth 1| shuf -n1) >> $HOME/.config/alacritty/alacritty.yml
}

# change font
font () {
  IFS=$'\t' ; read FONT STYLE <<< $(fc-list | sed -E 's|^.*\.[a-z]*: ||; s|:style=(.*)| (\1)|' | sort | uniq | dmenu -i -l 5 -fn "Noto Sans Mono Black" -sb "#16a085" | sed 's/)//; s/(/	/')
  [ -z $FONT ] && exit 1
  [ -z $(grep '^font:' $HOME/.config/alacritty/alacritty.yml) ] && enable_font $FONT	$STYLE && exit
  LINE=$(grep -n '^    style:' .config/alacritty/alacritty.yml | cut -d ":" -f1 | head -1)
  sed -i "s/^    family:.*/    family: $FONT/" $HOME/.config/alacritty/alacritty.yml
  sed -i "${LINE}s/^    style:.*/    style: $STYLE/" $HOME/.config/alacritty/alacritty.yml
}

# enable font field
enable_font () {
  echo -e "font:\n  normal:\n    family: $1\n    style: $2\n  bold:\n    family: $1\n    style: Bold\n  italic:\n    family: $1\n    style: Ialic\n  bold_italic:\n    family: $1\n    style: Bold Italic\n" >> $HOME/.config/alacritty/alacritty.yml 
}

# change font size
font_size () {
  [ -z "$(grep '^  size:' $HOME/.config/alacritty/alacritty.yml)" ] && echo "  size: 11.0" >> $HOME/.config/alacritty/alacritty.yml
  FONT=($(grep -o '  size: .*$'  $HOME/.config/alacritty/alacritty.yml | sed -E 's/^  size: ([0-9]*).([0-9])/\1 \2/'))
  SIZE=$((${FONT[0]}$1))
  sed -i "s/^  size: .*$/  size: ${SIZE}\.${FONT[1]}/" $HOME/.config/alacritty/alacritty.yml
}


# create backup
backup () {
  cp $HOME/.config/alacritty/alacritty.{yml,yml~}
}

# restore backup
restore_backup () {
  cp $HOME/.config/alacritty/alacritty.{yml~,yml}
}

size () {
  [ -z $(grep '^size:' $HOME/.config/alacritty/alacritty.yml) ] && echo "size: 11.0" >> $HOME/.config/alacritty/alacritty.yml && exit
}
case $1 in
  -i|--opacity+) opacity +1;;
  -d|--opacity-) opacity -1;;
  --font+) font_size +1;;
  --font-) font_size -1;;
  -d|--download-theme) get_themes;;
  -t|--random-theme) set_theme;;
  -c|--choose-theme) pick_theme;;
  -b|--backup) backup;;
  -r|--restore) restore_backup;;
  -f|--change-font) font;;
esac
